language: rust

rust:
    - stable
    - beta
    - nightly

install:
    - sudo apt-get install libtagc0-dev

cache: cargo

script:
    - cargo build -v
    - cargo build -v --features "use-pkgconfig"
    - cargo test -v
    - cargo doc -v
