language: rust

rust:
    - stable
    - beta
    - nightly

install:
    - sudo apt-get install libtag1-dev libtagc0-dev

script:
    - cargo build -v
    - cargo build -v --features "use-pkgconfig"
    - cargo test -v
    - cargo doc -v
